name: Delete Exchange Rate

on:
  schedule:
    - cron: "37 2,10 1 * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    concurrency:
      group: db-refresh-scheduler
      cancel-in-progress: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Debug workflow file
        run: |
          echo "===== WORKFLOW FILE ====="
          cat .github/workflows/scheduler_delete_exchange_rate.yml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

          pip install sqlalchemy
          pip install python-dotenv
          pip install pandas

      - name: Debug installed packages
        run: |
          echo "===== INSTALLED PACKAGES ====="
          pip list

      - name: Run scheduler script
        env:
          NEON_DB_PASSWORD: ${{ secrets.NEON_DB_PASSWORD }}
          NEON_DB_ENDPOINT: ${{ secrets.NEON_DB_ENDPOINT }}
        run: |
          python refresh_delete_exchange_rate_scheduler.py